---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Novo.
--- DateTime: 2023/4/22 14:02
---
local keys = KEYS
local time = tonumber(ARGV[1])
local count = tonumber(ARGV[2])
local values = redis.call('mget', unpack(keys))
local filterKeys = { }  -- 存储需要去重的key
-- 遍历值数组，对每个值进行操作
for i, value in ipairs(values) do
    local numValue = tonumber(value)
    if numValue ~= nil and numValue >= count
    then
        -- 此前发送过相同内容 且发送次数大于count 需要去重
        -- table.insert(filterKeys, "a")
        -- 这里是序列化的问题 不手动拼接可能会报错"\""
        ---table.insert(filterKeys, "abc")，
        ---Redis 解释器会将 abc 当做一个变量名或者一个函数名来解释，因此会报错。
        ---因为在 Redis 中，所有不被双引号包围的字符串都会被当做变量名或者函数名来解释。
        ---
        table.insert(filterKeys, "\"" .. keys[i] .. "\"")
    else
        -- numValue为空或者小于等于count
        -- 不满足去重条件的将count自增1并设置过期时间
        redis.call('incr', keys[i])
        redis.call('expire', keys[i], time)
    end
end

return filterKeys  -- 返回需要过滤的key
